config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get 'home/index'

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"



  root to: "main#index"
  
  # Defines the root path route ("/")
  # root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one :emergency_contact, class_name: "Contact", foreign_key: :contact_id

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
#email:string
#password_digest::string
#
#password:string virtual
#password_confirmation:string virtual

class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to contact_url(@contact), notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :street_address, :city, :state, :zip_code, :birthday, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        if session[:user_id]
        @user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end


    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account"
        else
            render :new, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = @user_id
            redirect_to root_path, notice: "Logged in successfully"
        else
            flash.now[:alert] = "Invalid email or password"
            render :new, status: :unprocessable_entity
        end
    end


    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>">
  <div class="bg-white shadow rounded-lg mt-10 p-10">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="lg:text-center">
      <h2 class="text-base text-indigo-600 font-semibold tracking-wide uppercase">Contact</h2>
    
      <p class="mt-2 text-3xl leading-8 font-extrabold tracking-tight text-gray-900 sm:text-4xl">
        <%= contact.first_name %> <%= contact.last_name %>
      </p>
      <div class="mt-5 text-base leading-normal text-gray-600 flex justify-center items-center">
        <%= contact.relationship&.titleize %>
      </div>
      <div class="text-sm leading-normal text-gray-400 flex justify-center items-center">
                <svg viewBox="0 0 24 24" class="mr-1" width="16" height="16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
                <%= contact.city %>, <%= contact.state %>
        </div>
    </div>

    <div class="mt-10">
      <dl class="space-y-10 md:space-y-0 md:grid md:grid-cols-4 md:gap-x-8 md:gap-y-10">
        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-9 w-9 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/phone -->
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
            </div>
            <p class="ml-12 text-lg leading-6 font-medium text-gray-900">Phone:</p>
          </dt>
          <dd class="mt-2 ml-12 text-base text-gray-500"><%= contact.phone %></dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-9 w-9 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/inbox -->
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
              </svg>
            </div>
            <p class="ml-12 text-lg leading-6 font-medium text-gray-900">Email:</p>
          </dt>
          <dd class="mt-2 ml-12 text-base text-gray-500"><%= contact.email %></dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-9 w-9 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/home -->
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
            </div>
            <p class="ml-12 text-lg leading-6 font-medium text-gray-900">Address:</p>
          </dt>
          <dd class="mt-2 ml-12 text-base text-gray-500"><%= contact.street_address %><br> <%= contact.city %>, <%= contact.state %> <%= contact.zip_code %></dd>
        </div>

        <div class="relative">
          <dt>
            <div class="absolute flex items-center justify-center h-9 w-9 rounded-md bg-blue-500 text-white">
              <!-- Heroicon name: outline/cake -->
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.701 2.701 0 00-1.5-.454M9 6v2m3-2v2m3-2v2M9 3h.01M12 3h.01M15 3h.01M21 21v-7a2 2 0 00-2-2H5a2 2 0 00-2 2v7h18zm-3-9v-2a2 2 0 00-2-2H8a2 2 0 00-2 2v2h12z" />
              </svg>
            </div>
            <p class="ml-12 text-lg leading-6 font-medium text-gray-900">Birthday</p>
          </dt>
          <dd class="mt-2 ml-12 text-base text-gray-500"><%= contact.birthday %></dd>
        </div>
      </dl>
    </div>

    <div class="relative">
      <dt>
        <div class="absolute flex items-center justify-center h-9 w-9 rounded-md bg-blue-500 text-white">
          <!-- Heroicon name: outline/home -->
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
          </svg>
        </div>
        <p class="ml-12 text-lg leading-6 font-medium text-gray-900">Emergency Contact</p>
      </dt>
      <dd class="mt-2 ml-12 text-base text-gray-500"><%= link_to contact.emergency_contact.full_name, contact_path(contact), class: "" %></dd>
    </div>

    <p class="mt-4 max-w-2xl text-xl text-gray-500 lg:mx-auto"><%= contact.note %></p>
  </div>
  <div class="flex items-center justify-center mt-10 ">
  <% if action_name != "show" %>
    <%= link_to "Show this contact", contact, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this contact', edit_contact_path(contact), class: "rounded-lg py-3 ml-2 px-5 bg-blue-500 text-white inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
  </div>
</div>
<!-- Default Contact Form-->
<!--
<div id="<%= dom_id contact %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">First name:</strong>
    <%= contact.first_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Last name:</strong>
    <%= contact.last_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= contact.phone %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Street address:</strong>
    <%= contact.street_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">City:</strong>
    <%= contact.city %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">State:</strong>
    <%= contact.state %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Zip code:</strong>
    <%= contact.zip_code %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Birthday:</strong>
    <%= contact.birthday %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Note:</strong>
    <%= contact.note %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this contact", contact, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this contact', edit_contact_path(contact), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>
-->

app/views/contacts/_form.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap -mx-2 my-5 space-y-4 md:space-y-0">
    <div class="w-full px-2 md:w-1/3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Sam" %>
    </div>

    <div class="w-full px-2 md:w-1/3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Jackson"  %>
    </div>

    <div class="w-full px-2 md:w -1/3">
      <%= form.label :relationship %>
      <%= form.text_field :relationship, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Coworker" %>
    </div>
  </div>

  <div class="flex flex-wrap -mx-2 my-5 space-y-4 md:space-y-0">

    <div class="w-full px-2 md:w-1/3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "name@email.com"  %>
    </div>

    <div class="w-full px-2 md:w-1/3">
      <%= form.label :phone %>
      <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "111-222-3333"  %>
    </div>

    <div class="w-full px-2 md:w-1/3">
      <%= form.label :birthday %>
      <%= form.date_field :birthday, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

  </div>
  <div class="flex flex-wrap -mx-2 my-5 space-y-4 md:space-y-0">

    <div class="w-full px-2 md:w-1/4">
      <%= form.label :street_address %>
      <%= form.text_field :street_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "1234 Main St."  %>
    </div>
    <div class="w-full px-2 md:w-1/4">
      <%= form.label :city %>
      <%= form.text_field :city, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Columbus"  %>
    </div>
    <div class="w-full px-2 md:w-1/4">
      <%= form.label :state %>
      <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Ohio "  %>
    </div>
    <div class="w-full px-2 md:w-1/4">
      <%= form.label :zip_code %>
      <%= form.text_field :zip_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "43215"  %>
    </div>
  </div>
  <div class="my-5">
    <%= form.label :contact_id, "Emergency Contact" %>
    <%= form.select :contact_id,  options_for_select(Contact.all.collect {|c| [ "#{c.first_name} #{c.last_name}", c.id ] }, []), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"  %>
  </div>
  <div class="my-5">
    <%= form.label :general_note %>
    <%= form.text_field :general_note, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Sam is super fun!"  %>
  </div>
  <div class="my-5">
    <%= form.label :user_photo %>
    <%= form.file_field :avatar, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Sam is super fun!"  %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Show this contact", @contact, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 shadow inline-block font-medium" %>
  <%= link_to "Back to Contacts", contacts_path, class: "ml-2 rounded-lg py-3 px-5 shadow text-white bg-green-500 transition colors hover:bg-green-700 inline-block font-medium" %>
</div>

app/views/contacts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Contacts</h1>
    <%= link_to 'New contact', new_contact_path, class: "rounded-lg py-3 px-5 shadow bg-green-500 transition colors hover:bg-green-700 text-white block font-medium" %>
  </div>

  <div id="contacts" class="min-w-full">
    <%= render @contacts %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to 'Back to contacts', contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/contacts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @contact %>

    <%= link_to 'Edit this contact', edit_contact_path(@contact), class: "mt-2 rounded-lg py-3 px-5 text-white bg-green-500 transition colors hover:bg-green-700 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Delete this contact', contact_path(@contact), method: :delete, class: "mt-2 rounded-lg py-3 px-5 shadow bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to contacts', contacts_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-500 transition colors hover:bg-blue-600 shadow text-white shadow inline-block font-medium" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="fixed top-0 left-0 bg-white w-full shadow">
  <div class="container m-auto flex justify-between items-center text-gray-700">
    <h1 class="pl-8 py-4 text-xl font-bold">ADDRESS BOOK</h1>
    <ul class="hidden md:flex items-center pr-10 text-base font-semibold cursor-pointer">
      <li>
        <%= link_to "Home", root_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
      </li>
      <li>
        <%= link_to "Contacts", contacts_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
      </li>
     
      <li>
        <%= link_to "Add Contact", new_contact_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
      </li>
      <li>
        <%= link_to "Sign In", sign_in_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
      </li>
      <li>
        <%= link_to "Sign up", sign_up_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
      </li>
      <div class="ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white shadow bg-green-600 transition colors hover:bg-green-700" ><%= button_to "Logout",  logout_path, method: :delete %></div>
    </ul>
    <button class="block md:hidden py-3 px-4 mx-2 rounded focus:outline-none hover:bg-gray-200 group"> 
      <div class="w-5 h-1 bg-gray-600 mb-1"></div>
      <div class="w-5 h-1 bg-gray-600 mb-1"></div>
      <div class="w-5 h-1 bg-gray-600"></div>
      <div class="absolute top-0 -right-full h-screen w-8/12 bg-white border opacity-0
      group-focus:right-0 group-focus:opacity-100 transition-all duration-300">
        <ul class="flex flex-col items-center w-full text-base cursor-pointer pt-10">
          <li>
            <%= link_to "Home", root_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
          </li>
          <li>
            <%= link_to "Contacts", contacts_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
          </li>
     
          <li>
            <%= link_to "Add Contact", new_contact_path, class:"nav-link block pr-2 lg:px-2 py-2 text-gray-500 transition colors hover:text-gray-900 focus:text-gray-700 transition duration-150 ease-in-out" %>
          </li>
        </ul>
      </div>
    </button>
  </div>
</nav>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="mx-auto">
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://cdn.tailwindcss.com"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'home/header'%>
    <main class="container mx-auto py-24 px-5">
      <!--<% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>-->
      <%= yield %>
    </main>
  </body>
</html>

app/views/main/index.html.erb
<div class="text-center bg-gray-50 text-gray-800 py-24 px-6">
      <h1 class="text-5xl md:text-6xl xl:text-7xl font-bold tracking-tight mb-12">The best place to keep <br /><span class="text-blue-600">your contacts</span></h1>
      <%= link_to "Get Started", sign_up_path, class: "ml-2 rounded-lg py-3 px-7 bg-gray-100 shadow inline-block font-medium" %>
      <%= link_to "Log In", sign_in_path, class: "ml-2 rounded-lg py-3 px-7 shadow text-white bg-green-500 transition colors hover:bg-green-700 inline-block font-medium" %>
      
</div>